import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'
import { registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { getRequests, deleteRequest } from './services/indexedDB'

cleanupOutdatedCaches()

self.skipWaiting()
clientsClaim()

// Precache all assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://vite-pwa-org.netlify.app/guide/inject-manifest.html
precacheAndRoute(self.__WB_MANIFEST)

// Cache Google Fonts
registerRoute(
    /^https:\/\/fonts\.googleapis\.com\/.*/i,
    new CacheFirst({
        cacheName: 'google-fonts-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365 // 365 days
            })
        ]
    })
)

registerRoute(
    /^https:\/\/fonts\.gstatic\.com\/.*/i,
    new CacheFirst({
        cacheName: 'gstatic-fonts-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365 // 365 days
            })
        ]
    })
)

// API Caching
registerRoute(
    /^\/api\/.*/i,
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 50,
                maxAgeSeconds: 60 * 60 * 24 // 1 day
            })
        ],
        networkTimeoutSeconds: 10
    })
)

// Background Sync Logic
self.addEventListener('sync', (event) => {
    if (event.tag === 'sync-offline-requests') {
        event.waitUntil(syncOfflineRequests())
    }
})

async function syncOfflineRequests() {
    console.log('Syncing offline requests...')
    try {
        const requests = await getRequests()

        for (const req of requests) {
            try {
                console.log(`Replaying request: ${req.method} ${req.url}`)

                const fetchOptions = {
                    method: req.method,
                    headers: req.headers,
                    body: req.data ? JSON.stringify(req.data) : undefined
                }

                // Remove Content-Type if it's already in headers to avoid duplication or boundary issues
                // but usually axios sets it. However, fetch body needs string if JSON.
                // If the stored headers imply JSON, we need to make sure body is stringified.
                // Assuming axios data was an object.

                const response = await fetch(req.url, fetchOptions)

                if (response.ok) {
                    console.log(`Request successful: ${req.url}`)
                    await deleteRequest(req.id)
                } else {
                    console.error(`Request failed with status ${response.status}: ${req.url}`)
                    // Decide whether to keep it or delete it. For now, we might keep it to retry later?
                    // Or maybe delete it to avoid infinite loops if it's a 4xx error.
                    if (response.status >= 400 && response.status < 500) {
                        await deleteRequest(req.id) // Client error, don't retry
                    }
                }
            } catch (error) {
                console.error(`Failed to replay request ${req.url}:`, error)
                // Network error likely, keep in DB for next sync
            }
        }
    } catch (error) {
        console.error('Error in syncOfflineRequests:', error)
    }
}
